spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3307/transportador
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
