spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://localhost:3307/fornecedor'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


